data/mainnet/pools.js
Tiny update adding swap fees for YEL-ETH, just looking through the new files. Will have a better look soon!
=> Add trading APY for YEL-ETH

data/mainnet/tokens.js
Updating the Convex fee factor as discussed. For all currently released Convex strategies.
=> Update Convex fee factor

data/mainnet/tokens.js
Removed TBTC from new.
Added PHTR vaults to new.
Added categories to relevant UniV3 vaults.
=> Updates to token.js

data/mainnet/tokens.js
Added the "inactive" tag to the 3 vaults moved to inactive last week.
=> Set vaults inactive

data/mainnet/pools.js
I think this might solve the issue that fYEL rewards are not showing in the UI.
=> Potential fix fYEL reward UI

data/mainnet/addresses.json, data/mainnet/tokens.js
Also removes quick icon from IFARM-QUICK pool
=> Update quickswap APY calc to use dQuick

data/mainnet/addresses.json, data/mainnet/tokens.js
This updates the fox-weth rewardPool to update the APY calculation and reactivates it in the UI.
=> Reactivate Fox vault

src/lib/web3/contracts/vault/contract.json, src/vaults/trading-apys/implementations/univ3-v3.js
=> Fallback to old implementation for old UniV3 vaults

src/vaults/trading-apys/implementations/lp.js
apy.vision slightly changed the structure of their stats endpoint, implementation updated to return swap fees correctly again.
=> Update lp trading fee implementation

data/mainnet/tokens.js
'New' prefix removed for Don, two CRV vaults and shapeshift.
=> remove new prefix

data/mainnet/tokens.js
Updating APY calculation for pending strategy change, which will change YEL-WETH vault from hodling to compounding.
=> Update YEL-WETH APY for strategy update

data/mainnet/tokens.js
This can be merged immediately
=> Update BAL rewards for USDC/WETH/BAL/WMATIC pool

.eslintrc, .gitattributes, data/mainnet/pools.js, data/mainnet/tokens.js, src/vaults/apys/implementations/univ3-seth2.js
APY type UNIV3--> univ3-seth2. 
SharePriceChangeTrading instead SharePriceChangeLiquidation. 
Trading APY vor seth3-eth vault --> 0. 
apyDescriptionOverride added into that vault.
=> seth2 apy calculation change

cron/bsc/hardhat.config.js, data/mainnet/addresses.json
It's an active vault, doing okay. Should be harvested at least weekly.
=> Change USDP harvest setting

src/vaults/trading-apys/implementations/univ3-v3.js
This should mitigate flunctuating apy caused by deposits and/or withdrawals
=> UniV3-v3 trading apy calc: Time-weight TVL since last harvest

data/mainnet/pools.js, src/pools/utils.js
From tomorrow's distribution, DON rewards will no longer be vested.
=> Don rewards no longer vested

data/mainnet/tokens.js
Move new crv:cvxcrv vault to the top and remove YEL vaults from `isNew`
=> Move new vault to top

src/lib/third-party/balancer.js, src/lib/web3/contracts/index.js, src/vaults/trading-apys/implementations/lp.js
Calculates the numbers we got through their subgraph on-chain instead for Polygon.
=> Balancer bug fix

data/mainnet/tokens.js
These emission changes has already taken place
=> Update BAL rewards

src/runtime/pollers.js, src/runtime/router/index.js, test/integration/happy-path.js
Decided to try and work on something a bit different. Wasn't really any ask for it, and not sure if it's useful, but I added some API endpoints that return the weekly USD values going to buybacks. Thought it could maybe come in handy for TFRs weekly analysis, but did not actually discuss that with them lol
Anyways, first time I did something like this, so not sure if everything I did makes sense. Please have a look if you think this could be useful. If not, no problem :D
=> Add buybacks endpoints

data/mainnet/addresses.json, data/mainnet/pools.js, data/mainnet/tokens.js
Updates for new AUR reward program.
Probably best to only push this after the strategy updates are through.
=> New AUR rewards

data/mainnet/addresses.json, data/mainnet/pools.js, data/mainnet/tokens.js
Please also check-out the updated needed on-chain: https://github.com/harvest-finance/harvest-strategy-polygon/pull/30
=> Update DEN/4EUR strategies

data/mainnet/pools.js
Reverts harvest-finance/harvest-api#223
=> Reintroducing notional

data/mainnet/pools.js, src/lib/third-party/balancer.js, src/prices/implementations/balancer.js, src/vaults/trading-apys/implementations/balancer-boost-info.json, src/vaults/trading-apys/implementations/balancer-boost.js, src/vaults/trading-apys/implementations/lp.js, src/vaults/trading-apys/index.js
=> Add balancer boost APY

src/lib/constants.js
Fixed error thrown because we reduced hardwork frequency to once in 14 days
=> Fix historical iFARM apy

data/mainnet/addresses.json
Reverts harvest-finance/harvest-api#251
=> Revert "Change hardwork settings"

src/lib/constants.js
Reverts harvest-finance/harvest-api#249
=> Revert "Fix historical iFARM apy"
